### ISSUE TITLE
AttributeError: 'scipy.spatial.transform._rotation.Rotation' object has no attribute 'as_dcm'

### ISSUE THREAD

**Issue by saurtone** [ZiadElmassik/CADCD_TO_KITTI_COMPLETE#2]
python cadc_kitti_convert_final.py

Traceback (most recent call last):
  File "cadc_kitti_convert_final.py", line 787, in <module>
    write_all_annotations(cam)
  File "cadc_kitti_convert_final.py", line 767, in write_all_annotations
    write_txt_annotation(frame,cam,out_dir,mode,image_dir,ddir,sequence,drive_and_sequence, current_frame_train, current_frame_test)
  File "cadc_kitti_convert_final.py", line 366, in write_txt_annotation
    make_calib_file(calib, calib_target_path, image_dir, frame)
  File "cadc_kitti_convert_final.py", line 166, in make_calib_file
    rot_matrix = np.array(R.from_euler('xyz', [newPoint[0], newPoint[1], newPoint[2]]).as_dcm()) #ORIGINAL
AttributeError: 'scipy.spatial.transform._rotation.Rotation' object has no attribute 'as_dcm'

**Comment by saurtone** [comment]
解决了。as_dcm改成as_matrix
